import * as fs from 'node:fs';
import * as path from 'node:path';
import sharp from 'sharp';

const SCRAPER_OUTPUT = path.join(
  process.env.HOME ?? '',
  'linkedin-scraper/output',
);
const OUTPUT_IMAGES = path.join(
  process.cwd(),
  'public/assets/images/hack-25/linkedin',
);
const OUTPUT_TS = path.join(
  process.cwd(),
  'app/[locale]/tour/sponsor/linkedin-posts.ts',
);

interface PostJson {
  url: string;
  author_name: string;
  author_subtitle: string;
  date_published: string;
  content: string;
  reaction_count: number;
  comment_count: number;
  attachments: string[];
}

interface LinkedInPost {
  url: string;
  authorName: string;
  authorSubtitle: string;
  authorProfilePicture: string;
  datePublished: string;
  content: string;
  reactionCount: number;
  commentCount: number;
  images: string[];
}

async function main() {
  fs.mkdirSync(OUTPUT_IMAGES, { recursive: true });

  const dirs = fs.readdirSync(SCRAPER_OUTPUT).filter((d) => {
    const full = path.join(SCRAPER_OUTPUT, d);
    return fs.statSync(full).isDirectory();
  });

  const posts: LinkedInPost[] = [];

  for (const dir of dirs) {
    const dirPath = path.join(SCRAPER_OUTPUT, dir);
    const jsonPath = path.join(dirPath, 'post.json');

    if (!fs.existsSync(jsonPath)) {
      console.warn(`Skipping ${dir} — no post.json`);
      continue;
    }

    const raw = JSON.parse(fs.readFileSync(jsonPath, 'utf-8')) as PostJson;
    const slug = dir
      .replace(/[^a-z0-9]/gi, '-')
      .toLowerCase()
      .slice(0, 60);

    // Profile picture
    const profileSrcPath = path.join(dirPath, 'profile_picture.jpg');
    let profileWebpPath = '';
    if (fs.existsSync(profileSrcPath)) {
      const destFilename = `${slug}_profile.webp`;
      const destPath = path.join(OUTPUT_IMAGES, destFilename);
      await sharp(profileSrcPath)
        .resize(200, 200, { fit: 'cover' })
        .webp({ quality: 80 })
        .toFile(destPath);
      profileWebpPath = `/assets/images/hack-25/linkedin/${destFilename}`;
    }

    // Post images
    const imageWebpPaths: string[] = [];
    const picAttachments = (raw.attachments ?? []).filter(
      (a) =>
        a.startsWith('pic') &&
        (a.endsWith('.jpg') || a.endsWith('.png') || a.endsWith('.jpeg')),
    );

    for (let i = 0; i < picAttachments.length; i++) {
      const picFilename = picAttachments[i];
      const picSrcPath = path.join(dirPath, picFilename);
      if (!fs.existsSync(picSrcPath)) continue;

      const destFilename = `${slug}_pic${i + 1}.webp`;
      const destPath = path.join(OUTPUT_IMAGES, destFilename);
      await sharp(picSrcPath)
        .resize(800, undefined, { fit: 'inside', withoutEnlargement: true })
        .webp({ quality: 80 })
        .toFile(destPath);
      imageWebpPaths.push(`/assets/images/hack-25/linkedin/${destFilename}`);
    }

    posts.push({
      url: raw.url,
      authorName: raw.author_name,
      authorSubtitle: raw.author_subtitle,
      authorProfilePicture: profileWebpPath,
      datePublished: raw.date_published,
      content: raw.content,
      reactionCount: raw.reaction_count,
      commentCount: raw.comment_count,
      images: imageWebpPaths,
    });

    console.log(`✓ ${raw.author_name} (${imageWebpPaths.length} images)`);
  }

  // Generate TypeScript file
  const tsContent = `// Auto-generated by src/lib/dev/scripts/import-linkedin-posts-hack25.ts
// Do not edit manually

export interface LinkedInPost {
  url: string;
  authorName: string;
  authorSubtitle: string;
  authorProfilePicture: string;
  datePublished: string;
  content: string;
  reactionCount: number;
  commentCount: number;
  images: string[];
}

export const linkedinPosts: LinkedInPost[] = ${JSON.stringify(posts, null, 2)};
`;

  fs.writeFileSync(OUTPUT_TS, tsContent, 'utf-8');
  console.log(`\nWrote ${posts.length} posts to ${OUTPUT_TS}`);
  console.log(`Images saved to ${OUTPUT_IMAGES}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
