"""Build /24's personal pages; panel geometry is retained in source/panel.svg.
Content comes from this site's info/index.html and existing blog posts.
Run from any directory: python3 /path/to/24/build.py
"""
from pathlib import Path
import re, html
ROOT=Path(__file__).resolve().parent
SITE=ROOT.parent
source=(ROOT/'source/panel.svg').read_text()
E=html.escape
sections=[('about','About'),('projects','Projects'),('blog','Blog'),('reading','Reading'),('contact','Contact')]
projects=[
 ('themis','themis.lat','https://themis.lat/','A tool to find corruption in Chile’s government contracting. Second place out of 200 hackers, with 1,000+ applicants.','CIVIC TECH / CHILE'),
 ('indies','indies.la','https://indies.la/','A community of builders in Latin America. 2,000 members, hackathons and cool sponsors.','COMMUNITY / LATAM'),
 ('kernel','kernel','https://kernel.platan.us/','An angel squad for Latin America.','VENTURE / LATAM'),
 ('amigos','amigos.sh','https://amigos.sh/','A microgrant fund for young individuals addressing important problems.','MICROGRANTS'),
 ('hack-latam','hack@latam','https://hack.indies.la/','A hackathon for social impact: 1,300 applicants, $6,000 in cash and five countries at the same time.','HACKATHON / 05 COUNTRIES'),
 ('platanus','platanus hack','https://hack.platan.us/','An in-person hackathon across five countries. 36 hours to build.','HACKATHON / 36 HOURS'),
 ('events','events','https://luma.com/user/natochi','I love doing meetups. You cannot imagine the money I’ve spent on pizzas.','MEETUPS / PIZZA')]
def a(url,label,cls=''):
 external=url.startswith('http');return f'<a href="{E(url,quote=True)}"'+(' target="_blank" rel="noopener noreferrer"' if external else '')+(f' class="{cls}"' if cls else '')+'>'+label+(' <span aria-hidden="true">↗</span>' if external else '')+'</a>'
def dotted(left,right,n=43):return left+'.'*max(2,n-len(left)-len(right))+right
# Only text content, accessibility metadata, and link wrappers change on the home panel.
changes={}
def change(x,y,label,href=None,aria=None):changes[(str(x),str(y))]=(label,href,aria)
change(8,14,'NATOCHI / NACHO BERNARDO','/24/about/','About Nacho Bernardo')
change(8,24,'PERSONAL TERMINAL / SANTIAGO, CL')
profile=[('BASE: SANTIAGO DE CHILE','ONLINE'),('FOCUS: STARTUPS & VENTURES','GROWTH'),('BUILDING BUSINESSES','6 YEARS'),('COMMUNITIES & COOL THINGS','ACTIVE'),('CURRENTLY @ PLATAN.US','OPEN'),('DROPOUT / ALWAYS LEARNING','ON'),('PROFILE / WHO AM I?','ENTER →')]
for i,(left,right) in enumerate(profile):change(8,45+i*10.2,dotted(left,right),'/24/about/')
change(8,126,'******** INTERESTS & CURRENT WORK ********')
focus=[('AI SAFETY','CURIOUS'),('COGNITIVE SCIENCE','CURIOUS'),('VENTURE CAPITAL','CURIOUS'),('COMMUNITIES & BORGES','ALWAYS'),('CURRENTLY: PLATAN.US','OPEN'),('CONTRACTING: KAIROS','OPEN'),('CONTRACTING: M3 FELLOWSHIP','OPEN'),('HELPING RUN: GENSTREAM','OPEN'),('GOT A QUESTION? BOOK 30 MIN','ENTER →')]
for i,(left,right) in enumerate(focus):change(8,136+i*10.2,dotted(left,right),'/24/contact/' if i==8 else '/24/about/')
change(8,238,'**************** PROJECTS ****************')
for i,(slug,name,url,desc,kind) in enumerate(projects):change(8,249+i*10.2,dotted(name.upper(),'OPEN →'),'/24/projects/#'+slug,'Read about '+name)
change(112,330,'ONLINE')
change(232,45,'CHANNEL MAP: PERSONAL')
for i,(slug,label) in enumerate(sections):change(232,55+i*10.2,f'{i+1:02} {label.upper():<10} OPEN →','/24/'+slug+'/',label)
change(232,116,'SANTIAGO / CHILE / CL')
change(8,452,'WRITING / PERSONAL LOG:','/24/blog/','Open the blog')
change(8,462.2,'ID  YEAR  TITLE')
change(8,472.4,'01  2026  SEGUIR ADELANTE','/24/blog/seguir-adelante/','Read seguir adelante')
change(8,482.6,'02  2025  2026 / A LIST','/24/blog/2026/','Read 2026')
change(8,492.8,'03  2026  ANGELSQUAD','/24/blog/angelsquad-for-latam/','Read angelsquad for latam')
change(8,513,'READ THE BLOG ........ →','/24/blog/')
change(8,524,'SEND A MESSAGE ....... →','/24/contact/')
change(0,0,'NACHO BERNARDO')
change(0,10,'SANTIAGO DE CHILE')
change(0,20,'NATOCHI /24')
change(0,30,'PERSONAL TERMINAL')
# Numeric y attributes generated by Python can contain floating-point tails.
def lookup(x,y):
 for (cx,cy),value in changes.items():
  if x==cx and abs(float(y)-float(cy))<.001:return value
 return None
def replace_text(match):
 attrs,old=match.group(1),match.group(2);x=re.search(r'\bx="([^"]+)"',attrs);y=re.search(r'\by="([^"]+)"',attrs)
 if not x or not y:return match.group(0)
 val=lookup(x.group(1),y.group(1))
 if not val:return match.group(0)
 label,href,aria=val
 result=f'<text{attrs}>{E(label)}</text>'
 if href:
  # Generous row targets; keep all source strokes/paths untouched.
  px=float(x.group(1));py=float(y.group(1));width=112 if px==232 else (127 if 449<=py<530 else 209)
  target=f'<rect class="hit-area" x="{px-2}" y="{py-8.8}" width="{width+4}" height="10.2" fill="transparent"/>'
  result=f'<a class="panel-link" href="{href}" aria-label="{E(aria or label.replace("."," "),quote=True)}">{target}{result}</a>'
 return result
panel=re.sub(r'<text([^>]*)>(.*?)</text>',replace_text,source,flags=re.S)
panel=panel.replace('role="img"','role="group"').replace('<title id="title">CMX-7500 GEN 2A RADCOMMS IMGU</title>','<title id="title">natochi — personal terminal</title>').replace(re.search(r'<desc.*?</desc>',panel,re.S).group(0),'<desc id="description">Nacho Bernardo, Santiago de Chile. Explore my profile, projects, writing, reading and contact channels.</desc>')
# The final scanline layer is decorative and must not intercept links.
panel=panel.replace('fill="url(#scan)"','fill="url(#scan)" pointer-events="none"')
head='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#000000"><link rel="icon" href="/favicon.svg">'''
home_css='''*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#000}body{min-height:100svh;display:grid;grid-template-columns:minmax(0,1fr);place-items:center;padding:28px 16px;color:#c7c7ce}main{width:352px;max-width:100%;line-height:0}svg{display:block;width:100%;height:auto;font-family:Menlo,Consolas,monospace;font-weight:400;letter-spacing:.05px}text{white-space:pre}.panel-link{cursor:pointer}.panel-link:hover text,.panel-link:focus-visible text{fill:#fff;text-decoration:underline}.panel-link:hover .hit-area,.panel-link:focus-visible .hit-area{fill:#ffffff16}.panel-link:focus-visible{outline:none}.panel-link:focus-visible .hit-area{stroke:#fff;stroke-width:.7}.skip{position:absolute;top:8px;left:12px;color:#eee;font:12px monospace;transform:translateY(-200%);line-height:1.5}.skip:focus{transform:none}@media(max-width:383px){body{padding:20px 12px}}@media(min-width:768px){body{padding:24px}main{width:min(560px,calc((100svh - 48px)*.5641025641))}}'''
(ROOT/'index.html').write_text(head+'<title>natochi — personal terminal</title><meta name="description" content="Nacho Bernardo. Building businesses, communities and cool things from Santiago de Chile."><style>'+home_css+'</style></head><body><a class="skip" href="/24/about/">Read my profile</a><main><!--email_off-->'+panel+'<!--/email_off--></main></body></html>')
# Reuse original instruments without redrawing their internal details.
def asset(name,viewbox,fragment):
 svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="'+viewbox+'"><style>text{font-family:Menlo,Consolas,monospace;font-weight:400;letter-spacing:.05px;white-space:pre}</style>'+re.search(r'<defs>.*?</defs>',source,re.S).group(0)+fragment+'</svg>'
 (ROOT/'assets'/name).write_text(svg)
asset('radar.svg','228 128 120 96',source[source.index('<circle cx="243"'):source.index('<text x="232" y="238"')])
asset('spectrum.svg','5 340 343 96',source[source.index('<g shape-rendering="crispEdges">'):source.index('<text x="8" y="452.0"')])
asset('identity.svg','164 4 53 25',source[source.index('<rect x="165"'):source.index('<text x="8" y="35"')])
css='''*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#000;color:#c7c7ce}body{min-height:100svh;padding:24px;display:grid;place-items:center;font:12px/1.7 Menlo,Consolas,monospace}a{color:inherit;text-underline-offset:4px}a:hover{color:#fff}a:focus-visible{outline:1px solid #fff;outline-offset:4px}button{font:inherit}.frame{width:min(100%,560px);height:min(920px,calc(100svh - 48px));min-height:420px;border:1px solid #aaaab0;background:#050609;display:grid;grid-template-rows:auto auto minmax(0,1fr) auto auto;position:relative}.masthead{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:16px 18px 13px;border-bottom:1px solid #aaaab0}.brand{text-decoration:none;font-size:11px;letter-spacing:.06em}.brand span{display:block;color:#888893;font-size:9px;letter-spacing:.03em}.identity{width:68px;height:32px}.navigation{display:flex;flex-wrap:wrap;gap:4px 14px;border-bottom:1px solid #777780;padding:10px 18px;font-size:10px;text-transform:uppercase;letter-spacing:.03em}.navigation a{text-decoration:none;white-space:nowrap}.navigation [aria-current=page]{color:#fff;text-decoration:underline}.reader{overflow:auto;overscroll-behavior:contain;scrollbar-width:thin;scrollbar-color:#777780 #050609;padding:24px 22px 28px;min-height:0}.eyebrow{font-size:9px;letter-spacing:.13em;color:#8e8e98;text-transform:uppercase;margin:0 0 10px}h1{font-size:25px;line-height:1.3;font-weight:400;letter-spacing:-.04em;margin:0 0 22px;overflow-wrap:anywhere}h2{font-size:13px;font-weight:400;line-height:1.5;margin:26px 0 12px;text-transform:uppercase;letter-spacing:.05em}p{margin:0 0 17px}.intro{font-size:14px;line-height:1.75;color:#dddde2}.muted{color:#8e8e98}.profile-layout{display:grid;grid-template-columns:minmax(0,1fr) 132px;gap:24px;align-items:start}.radar{width:132px;height:auto;margin-top:5px}.rule{border:0;border-top:1px dashed #6b6b73;margin:23px 0}.project,.entry,.book,.channel{padding:18px 0;border-bottom:1px dashed #64646c;scroll-margin-top:10px}.project:first-child,.entry:first-child{padding-top:0}.project h2,.book h2{margin:0 0 8px;font-size:15px;text-transform:none;letter-spacing:0}.project p{margin-bottom:10px}.index{font-size:9px;letter-spacing:.07em;color:#8e8e98;margin-bottom:7px}.entry{display:block;text-decoration:none}.entry h2{margin:4px 0 8px;text-transform:none;letter-spacing:0;font-size:17px;line-height:1.45}.entry p{margin:0;font-size:11px;color:#a0a0aa}.entry:hover h2{text-decoration:underline}.telemetry{border-top:1px solid #aaaab0;padding:6px 12px;display:flex;align-items:center;gap:18px;overflow:hidden}.spectrum{width:180px;max-width:45%;height:auto;opacity:.85}.telemetry-label{font-size:9px;letter-spacing:.05em;line-height:1.7}.telemetry-label span{color:#84848e}.status{border-top:1px solid #777780;padding:8px 18px;font-size:9px;display:flex;justify-content:space-between;gap:12px;letter-spacing:.04em}.status a{text-decoration:none}.article-body{font-size:13px;line-height:1.9}.article-body p{margin:0 0 20px}.article-body li{padding-left:3px;margin-bottom:9px}.article-body ul,.article-body ol{padding-left:21px}.article-body img{max-width:100%;height:auto}.article-body hr{border:0;border-top:1px dashed #666;margin:24px 0}.article-nav{border-top:1px dashed #666;padding-top:18px;margin-top:28px;display:flex;justify-content:space-between;gap:18px;font-size:10px}.channel{display:flex;justify-content:space-between;gap:20px;align-items:center}.channel a{font-size:13px}.channel span{font-size:10px;color:#8e8e98}.notice{border-left:1px solid #aaa;padding-left:12px;color:#a0a0aa;font-size:11px}.skip{position:absolute;left:16px;top:0;transform:translateY(-200%);z-index:2;background:#050609}.skip:focus{transform:none}@media(max-width:600px){body{padding:12px;font-size:12px}.frame{height:calc(100svh - 24px);min-height:360px}.masthead{padding:13px 14px}.navigation{padding:9px 14px;gap:5px 12px;font-size:9px}.reader{padding:22px 16px}.profile-layout{grid-template-columns:minmax(0,1fr) 85px;gap:13px}.radar{width:85px}.intro{font-size:12px}h1{font-size:23px}.telemetry-label{font-size:8px}.status{padding:8px 12px;font-size:8px}.channel{gap:8px}.channel a{font-size:11px}.channel span{font-size:8px}}@media(max-height:500px){body{display:block}.frame{margin:auto;height:650px;min-height:0}}'''
(ROOT/'assets/site.css').write_text(css)
def page(slug,title,content,active,description):
 nav=''.join(f'<a href="/24/{s}/"'+(' aria-current="page"' if s==active else '')+f'>{i+1:02} {label}</a>' for i,(s,label) in enumerate(sections))
 htmlpage=head+f'<title>{E(title)} — natochi</title><meta name="description" content="{E(description,quote=True)}"><link rel="stylesheet" href="/24/assets/site.css"></head><body><a class="skip" href="#content">Skip to content</a><main class="frame"><header class="masthead"><a class="brand" href="/24/">NATOCHI / NACHO BERNARDO<span>PERSONAL TERMINAL · SANTIAGO, CL</span></a><img class="identity" src="/24/assets/identity.svg" alt="" width="68" height="32"></header><nav class="navigation" aria-label="Sections">'+nav+'</nav><section class="reader" id="content" tabindex="0" aria-label="'+E(title,quote=True)+'">'+content+'</section><aside class="telemetry" aria-label="Terminal status"><img class="spectrum" src="/24/assets/spectrum.svg" alt="" width="180" height="50"><div class="telemetry-label">'+E(active.upper())+' / CHANNEL OPEN<br><span>SANTIAGO DE CHILE<br>NATOCHI.CV /24</span></div></aside><footer class="status"><a href="/24/">← MAIN TERMINAL</a><a href="/24/contact/">CONTACT →</a></footer></main></body></html>'
 dest=ROOT/slug/'index.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(htmlpage)
about='''<p class="eyebrow">01 / Profile</p><h1>natochi (╬`益´)</h1><div class="profile-layout"><div><p class="intro">I’m Nacho Bernardo. A dropout based in Santiago de Chile, focused on finding growth levers for startups, ventures and cool things ;).</p><p>Over the last six years, I’ve built businesses, communities and fun stuff at the places I’ve worked.</p></div><img class="radar" src="/24/assets/radar.svg" alt="" width="132" height="106"></div><hr class="rule"><h2>Current signals</h2><p>Currently at '''+a('https://platan.us/','platan.us')+'''.</p><p>Contracting at '''+a('https://kairos-project.org/','kairos')+' and '+a('https://m3fellowship.com/','m3 fellowship')+''', and helping run '''+a('https://genstream.org/','genstream')+'''.</p><h2>Interests</h2><p>AI safety, cognitive science, venture capital, community stuff and anything Borges related.</p><p>'''+a('/24/projects/','Explore my projects →')+'''</p><p>'''+a('/24/reading/','What I’m reading & watching →')+'</p>'
page('about','About',about,'about','Nacho Bernardo. Businesses, communities and cool things from Santiago de Chile.')
projecthtml='<p class="eyebrow">02 / Projects</p><h1>Things I’ve helped build.</h1><p class="muted">Businesses, communities, hackathons and experiments across Latin America.</p><div>'
for i,(slug,name,url,desc,kind) in enumerate(projects):projecthtml+=f'<article class="project" id="{slug}"><p class="index">{i+1:02} / {kind}</p><h2>{a(url,E(name))}</h2><p>{E(desc)}</p></article>'
page('projects','Projects',projecthtml+'</div>','projects','Communities, tools, grants and hackathons: projects by Nacho Bernardo.')
# Import actual articles without inventing or completing unfinished posts.
posts=[]
for slug in ['seguir-adelante','2026','angelsquad-for-latam','mental-models-for-not-knowing-what-the-fuck-your-doing']:
 s=(SITE/'blog'/slug/'index.html').read_text()
 title=re.search(r'<h1>(.*?)</h1>',s,re.S).group(1)
 date=re.search(r'<p class="date">(.*?)</p>',s,re.S).group(1)
 body=re.search(r'<div class="blog-content">(.*?)\n                </div>',s,re.S).group(1).strip()
 posts.append(dict(slug=slug,title=title,date=date,body=body))
excerpts={'seguir-adelante':'para admirar se necesita grandeza.','2026':'una lista para el año.','angelsquad-for-latam':'en venture capital','mental-models-for-not-knowing-what-the-fuck-your-doing':'writing this...'}
blog='<p class="eyebrow">03 / Writing</p><h1>Personal log.</h1><p class="muted">Notes, lists and things I’m still figuring out.</p><div>'
for i,p in enumerate(posts):blog+=f'<a class="entry" href="/24/blog/{p["slug"]}/"><span class="index">{i+1:02} / {p["date"]}</span><h2>{p["title"]} <span aria-hidden="true">→</span></h2><p>{E(excerpts[p["slug"]])}</p></a>'
page('blog','Blog',blog+'</div>','blog','Notes and writing by Nacho Bernardo.')
for i,p in enumerate(posts):
 content=f'<p class="eyebrow">03 / Personal log / {p["date"]}</p><h1>{p["title"]}</h1><article class="article-body" lang="'+('es' if p['slug'] in ['2026','seguir-adelante','angelsquad-for-latam'] else 'en')+'">'+p['body']+'</article>'
 nxt=posts[(i+1)%len(posts)]
 content+='<nav class="article-nav" aria-label="Articles">'+a('/24/blog/','← ALL WRITING')+a('/24/blog/'+nxt['slug']+'/','NEXT ENTRY →')+'</nav>'
 page('blog/'+p['slug'],html.unescape(p['title']),content,'blog',excerpts[p['slug']])
reading='<p class="eyebrow">04 / Reading & watching</p><h1>Current inputs.</h1><p class="muted">From my reading and watching list.</p><article class="book"><p class="index">01 / READING</p><h2>'+a('https://www.goodreads.com/book/show/18796.In_Search_of_Lost_Time','In Search of Lost Time')+'</h2><p>Marcel Proust.</p></article><article class="book"><p class="index">02 / WATCHING</p><h2>'+a('https://myanimelist.net/anime/52991/Sousou_no_Frieren','Sōsō no Frieren')+'</h2><p>Kanehito Yamada.</p></article><h2>Always on the radar</h2><p>AI safety, cognitive science, venture capital, communities — and anything Borges related.</p><img class="radar" src="/24/assets/radar.svg" alt="" width="132" height="106">'
page('reading','Reading & watching',reading,'reading','Reading, watching and interests from natochi’s personal list.')
contact='<p class="eyebrow">05 / Contact</p><h1>Open a channel.</h1><p class="intro">Got a question? Book 30 minutes, send an email or find me online.</p>'
for label,url,value in [('BOOK 30 MIN','https://cal.com/natochi','cal.com/natochi'),('EMAIL','mailto:ernesto@indies.cl','ernesto@indies.cl'),('LINKEDIN','https://www.linkedin.com/in/natochi/','/in/natochi'),('TWITTER / X','https://x.com/natochi_','@natochi_'),('EVENTS','https://luma.com/user/natochi','meetups & community')]:contact+='<div class="channel">'+a(url,label)+'<span>'+E(value)+'</span></div>'
contact+='<h2>Based in Santiago de Chile.</h2><p>Startups, ventures, communities and cool things.</p>'
page('contact','Contact',contact,'contact','Get in touch with Nacho Bernardo, or book 30 minutes.')
print('Built personal terminal, 5 section pages, and 4 article pages.')
